ORG 0
;CHANGE ALL RED
	
LOAD RED
OUT PXL_CA
	
LOOP:

  REFRESH: 
	
	IN Switches
	AND SwitchEight
	SHIFT -8
	OUT PXL_R
	OUT LEDs
	
	LOADI 0
	OUT PXL_A
	
	;Load WHITE Default Color
	LOAD WHITE
	STORE COLOR
	;Check 0th Switch
	IN Switches
	AND SwitchZero
	JZERO FIRSTROW
	;ELSE LOAD COLOR TO BE WRITTEN
	LOAD PURPLE
	STORE COLOR
	
	FIRSTROW:
		CALL ROWWRITER
	
	;Load WHITE Default Color
	LOAD WHITE
	STORE COLOR
	;Check 1st Switch
	IN Switches
	AND SWITCHONE
	JZERO SECONDROW
	;ELSE LOAD COLOR TO BE WRITTEN
	LOAD BLUE
	STORE COLOR	
		
	SECONDROW:
		CALL ROWWRITER
	
	;Load WHITE Default Color
	LOAD WHITE
	STORE COLOR
	;Check 2nd Switch
	IN Switches
	AND SWITCHTWO
	JZERO THIRDROW
	;ELSE LOAD COLOR TO BE WRITTEN
	LOAD GREEN
	STORE COLOR	
		
	THIRDROW:
		CALL ROWWRITER

	;Load WHITE Default Color
	LOAD WHITE
	STORE COLOR
	;Check 2nd Switch
	IN Switches
	AND SWITCHTHREE
	JZERO FOURTHROW
	;ELSE LOAD COLOR TO BE WRITTEN
	LOAD YELLOW
	STORE COLOR	
		
	FOURTHROW:
		CALL ROWWRITER
	
	;Load WHITE Default Color
	LOAD WHITE
	STORE COLOR
	;Check 2nd Switch
	IN Switches
	AND SWITCHFOUR
	JZERO FIFTHROW
	;ELSE LOAD COLOR TO BE WRITTEN
	LOAD ORANGE
	STORE COLOR	
		
	FIFTHROW:
		CALL ROWWRITER
		
	;Load WHITE Default Color
	LOAD WHITE
	STORE COLOR
	;Check 2nd Switch
	IN Switches
	AND SWITCHFIVE
	JZERO SIXTHROW
	;ELSE LOAD COLOR TO BE WRITTEN
	LOAD RED
	STORE COLOR	
		
	SIXTHROW:
		CALL ROWWRITER	
		
	
	
JUMP LOOP	
	
ROWWRITER:
	LOADI 32
	STORE COUNTER
	

	WRITELOOP:
		LOAD COUNTER
		JZERO  ENDWRITE
		ADDI -1
		STORE COUNTER
		
		
		LOAD COLOR
		OUT PXL_D
		JUMP WRITELOOP
	ENDWRITE:
		RETURN
	
	  
	RED: DW &HF800  
	ORANGE: DW &HFB40
	YELLOW: DW &HFFE5
	GREEN: DW &H17E0
	BLUE: DW &H297F
	PURPLE: DW &H981F
	WHITE: DW  &HFFFF
		
	PINK: DW &HF97C
	TEAL: DW &H2F9F
	
	PXL_A:     EQU &H0B0
	PXL_D:     EQU &H0B1
	PXL_CA:	   EQU &H0B2
	PXL_R:	   EQU &H0B3
	PXL_S:	   EQU &H0B4
	PXL_L:	   EQU &H0B5
	PXL_Red:   EQU &H0B6
	PXL_Green: EQU &H0B7
	PXL_Blue:  EQU &H0B8
	
	Switches:  EQU 000
	LEDs:      EQU 001
	Timer:     EQU 002
	
SwitchZero: DW  &B0000000000000001
SwitchOne: DW 	&B0000000000000010
SwitchTwo: DW 	&B0000000000000100
SwitchThree: DW &B0000000000001000
SwitchFour: DW 	&B0000000000010000
SwitchFive: DW 	&B0000000000100000
SwitchSix: DW 	&B0000000001000000
SwitchSeven: DW &B0000000010000000
SwitchEight: DW &B0000000100000000
SwitchNine: DW 	&B0000001000000000

COLOR: DW 0
COUNTER: DW 32

	